# Generated by Django 5.0.2 on 2024-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='authors_image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='contactnext',
            name='authors_image',
            field=models.ImageField(default=2, upload_to='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactnext',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactnext',
            name='title',
            field=models.CharField(default=1, max_length=212),
            preserve_default=False,
        ),
    ]
